### PR TITLE
Feature/spm support

### PR DESCRIPTION
**Pull request by arifinfrds**

### CODE REVIEW

**Comment by lutluthfi** [comment]
Before you make pull request again. Could you add gitignore, please? Because I forget to add that

**Comment by arifinfrds** [comment]
I will add the git ignore from this branch

**Comment by arifinfrds** [comment]
@lutluthfi I added gitignore file. But I don't know how to merge it to develop, can't find the button.

**Comment by lutluthfi** [comment]
> @lutluthfi I added gitignore file. But I don't know how to merge it to develop, can't find the button.

You should make a new pull request and close this pull request

**Pull request closed without merging**
